server:
    port: 8080

spring:
    redis:
        timeout: 1000ms
        database: 1
        host: 47.94.229.159
        password: redis123
        port: 6379
        lettuce:
            pool:
                max-idle: 5
                max-wait: -1ms
                max-active: 1000
                min-idle: 0
    datasource:
        name: blog
        url: jdbc:mysql://47.94.229.159:3306/Blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: mysql123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    http:
        encoding:
            charset: utf-8
            enabled: true
            force: true
    messages:
        encoding: UTF-8
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        cache: false
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8


    freemarker:
        cache: false
    devtools:
        remote:
            restart:
                enabled: true

mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: xyz.dsvshx.blog.entity
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count

#debug: true

# oss
oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: LTAI4FjACkPyL82MPkFpxagu
    keysecret: LDqgwj1fXJlN8slwlHVdM7DEMkHK6d
    bucketname: dsvshx
    filehost: file
