spring:
    redis:
        timeout: 100ms
        database: 1
        host: 127.0.0.1
        password: redis123
        port: 6379
        lettuce:
            pool:
                max-idle: 5
                max-wait: -1ms
                max-active: 1000
                min-idle: 0